### ISSUE TITLE
[Feature] Investigate implementing an abstract ToJSON class

### ISSUE THREAD

**Issue by Grabt234** [Sense-Scape/Chunk_Types#20]
This will allow to ToJSON module in the [Generic Modules](https://github.com/Sense-Scape/Generic_Modules) repo to query a chunk if it can be converted to JSON and then process or drop it.

**Comment by Grabt234** [comment]
- A derived chunk class should inherit from this abstract class. 
- This class should only implement a ToJSON() function that uses the nlohman JSON library
- The function shold take all the memeber variables, store the names and values in the json class.
- It should then return this json string.

**Comment by Grabt234** [comment]
Blocked on getting microphone hardware. Reallocating to myseld as I have nothing to do :)

**Comment by wolffshots** [comment]
> Blocked on getting microphone hardware. Reallocating to myseld as I have nothing to do :)

hahah alright
