### ISSUE TITLE
[Feature] Implement a ToJSON function in the WAV header struct

### ISSUE THREAD

**Issue by Grabt234** [Sense-Scape/Chunk_Types#34]
[This](https://www.geeksforgeeks.org/difference-c-structures-c-structures/) link shows how to implement a function in a structure.

The ToJSON function should work the same way as that implemented in the TimeChunk class. It may be used as a reference.

**Comment by Grabt234** [comment]
One should also implement testing of this function to close this issue

**Comment by wolffshots** [comment]
I vote to close this for #33

**Comment by Grabt234** [comment]
Closing with pull request #33
